buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21'
    }
}

allprojects {
    layout.buildDirectory = file("${System.getProperty('user.home')}/.gradle_builds/nayagi/${project.name}")
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
